

import React from 'react';
import {
  Loader2, Send, Zap, Lock, AlertCircle, LayoutGrid, CheckSquare,
  Settings, Sun, Moon, Plus, FileText, X, Upload, Trash2, Calendar,
  ChevronRight, ArrowRight, Image as ImageIcon, History,
  CheckCircle2, Circle, RotateCcw, GraduationCap, Activity, Brain,
  Paperclip, Sparkles, Undo2, Command, Trophy, Glasses, Dna, BookOpen,
  Camera, File, ClipboardList, Link, Mail, Bird, Bolt, BrainCircuit,
  Pencil, Palette, Globe, Monitor, Dumbbell, Languages, Library, Sigma,
  Calculator, Percent, UploadCloud, List, Flame, Clock3, BarChart3,
  TrendingUp, TrendingDown, Award, Menu, Lightbulb, Mic, MicOff, Target,
  AlertTriangle, Check
} from 'lucide-react';

export const Icons = {
  Spinner: ({ className }: { className?: string }) => <Loader2 className={`animate-spin ${className}`} />,
  Send: ({ className }: { className?: string }) => <Send className={className} />,
  Flash: ({ className }: { className?: string }) => <Zap className={className} />,
  Lock: ({ className }: { className?: string }) => <Lock className={className} />,
  Error: ({ className }: { className?: string }) => <AlertCircle className={className} />,
  Layout: ({ className }: { className?: string }) => <LayoutGrid className={className} />,
  CheckSquare: ({ className }: { className?: string }) => <CheckSquare className={className} />,
  Settings: ({ className }: { className?: string }) => <Settings className={className} />,
  Sun: ({ className }: { className?: string }) => <Sun className={className} />,
  Moon: ({ className }: { className?: string }) => <Moon className={className} />,
  Plus: ({ className }: { className?: string }) => <Plus className={className} />,
  FileText: ({ className }: { className?: string }) => <FileText className={className} />,
  X: ({ className }: { className?: string }) => <X className={className} />,
  Upload: ({ className }: { className?: string }) => <Upload className={className} />,
  Trash: ({ className }: { className?: string }) => <Trash2 className={className} />,
  Calendar: ({ className }: { className?: string }) => <Calendar className={className} />,
  ChevronRight: ({ className }: { className?: string }) => <ChevronRight className={className} />,
  ArrowRight: ({ className }: { className?: string }) => <ArrowRight className={className} />,
  Image: ({ className }: { className?: string }) => <ImageIcon className={className} />,
  History: ({ className }: { className?: string }) => <History className={className} />,
  Check: ({ className }: { className?: string }) => <CheckCircle2 className={className} />,
  Circle: ({ className }: { className?: string }) => <Circle className={className} />,
  Restore: ({ className }: { className?: string }) => <RotateCcw className={className} />,
  School: ({ className }: { className?: string }) => <GraduationCap className={className} />,
  Activity: ({ className }: { className?: string }) => <Activity className={className} />,
  Brain: ({ className }: { className?: string }) => <Brain className={className} />,
  Paperclip: ({ className }: { className?: string }) => <Paperclip className={className} />,
  Sparkles: ({ className }: { className?: string }) => <Sparkles className={className} />,
  Undo: ({ className }: { className?: string }) => <Undo2 className={className} />,
  Command: ({ className }: { className?: string }) => <Command className={className} />,
  Trophy: ({ className }: { className?: string }) => <Trophy className={className} />,
  Glasses: ({ className }: { className?: string }) => <Glasses className={className} />,
  Dna: ({ className }: { className?: string }) => <Dna className={className} />,
  BookOpen: ({ className }: { className?: string }) => <BookOpen className={className} />,
  Camera: ({ className }: { className?: string }) => <Camera className={className} />,
  File: ({ className }: { className?: string }) => <File className={className} />,
  Clipboard: ({ className }: { className?: string }) => <ClipboardList className={className} />,
  Link: ({ className }: { className?: string }) => <Link className={className} />,
  Mail: ({ className }: { className?: string }) => <Mail className={className} />,
  Eagle: ({ className }: { className?: string }) => <Bird className={className} />,
  Bolt: ({ className }: { className?: string }) => <Bolt className={className} />,
  BrainCircuit: ({ className }: { className?: string }) => <BrainCircuit className={className} />,
  Edit: ({ className }: { className?: string }) => <Pencil className={className} />,
  Palette: ({ className }: { className?: string }) => <Palette className={className} />,
  Globe: ({ className }: { className?: string }) => <Globe className={className} />,
  Monitor: ({ className }: { className?: string }) => <Monitor className={className} />,
  Dumbbell: ({ className }: { className?: string }) => <Dumbbell className={className} />,
  Languages: ({ className }: { className?: string }) => <Languages className={className} />,
  Library: ({ className }: { className?: string }) => <Library className={className} />,
  Sigma: ({ className }: { className?: string }) => <Sigma className={className} />,
  Calculator: ({ className }: { className?: string }) => <Calculator className={className} />,
  Percent: ({ className }: { className?: string }) => <Percent className={className} />,
  UploadCloud: ({ className }: { className?: string }) => <UploadCloud className={className} />,
  List: ({ className }: { className?: string }) => <List className={className} />,
  Flame: ({ className }: { className?: string }) => <Flame className={className} />,
  Clock: ({ className }: { className?: string }) => <Clock3 className={className} />,
  BarChart: ({ className }: { className?: string }) => <BarChart3 className={className} />,
  TrendingUp: ({ className }: { className?: string }) => <TrendingUp className={className} />,
  TrendingDown: ({ className }: { className?: string }) => <TrendingDown className={className} />,
  Award: ({ className }: { className?: string }) => <Award className={className} />,
  Menu: ({ className }: { className?: string }) => <Menu className={className} />,
  Lightbulb: ({ className }: { className?: string }) => <Lightbulb className={className} />,
  Mic: ({ className }: { className?: string }) => <Mic className={className} />,
  MicOff: ({ className }: { className?: string }) => <MicOff className={className} />,
  Target: ({ className }: { className?: string }) => <Target className={className} />,
};
